In [0]:
#Итоговая работа
#Работаем с набором данных MovieLens 100K Dataset 
#https://grouplens.org/datasets/movielens/100k/
#Вам нужны только файлы u.data, u.genre, u.info, u.item и u.occupation. 
#Это текстовые файлы, которые можно загрузить в pandas при помощи read_csv 
#с правильным набором параметров

In [0]:
#Загрузить данные в pandas
import pandas as pd

r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
data = pd.read_csv('u.data', header=None, sep='\t', skiprows=0, names=r_cols)

g_cols = ['genre', 'index']
genre = pd.read_csv('u.genre', sep='|', names=g_cols)

i_cols = ['amount', 'type']
info = pd.read_csv('u.info', header=None, sep=' ', names=i_cols)

m_cols = ['movie_id', 
          'title', 
          'release_date', 
          'video_release_date', 
          'imdb_url', 
          'unknown',
          'action',
          'adventure',
          'animation',
          'children\'s',
          'comedy',
          'crime',
          'documentary',
          'drama',
          'fantasy',
          'film-noir',
          'horror',
          'musical',
          'mystery',
          'romance',
          'sci-fi',
          'thriller',
          'war',
          'wester'
         ]
item = pd.read_csv('u.item', header=None, sep='|', encoding='latin-1', names=m_cols)

o_cols=['occupation']
occupation = pd.read_csv('u.occupation')

u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
user = pd.read_csv('u.user', sep='|', names=u_cols)

In [2]:
data.head(5)

   user_id  movie_id  rating  unix_timestamp
0      196       242       3       881250949
1      186       302       3       891717742
2       22       377       1       878887116
3      244        51       2       880606923
4      166       346       1       886397596

In [3]:
genre.head(8)

         genre  index
0      unknown      0
1       Action      1
2    Adventure      2
3    Animation      3
4   Children's      4
5       Comedy      5
6        Crime      6
7  Documentary      7

In [4]:
info.head(5)

   amount     type
0     943    users
1    1682    items
2  100000  ratings

In [5]:
item.head(5)

   movie_id              title release_date  ...  thriller war  wester
0         1   Toy Story (1995)  01-Jan-1995  ...         0   0       0
1         2   GoldenEye (1995)  01-Jan-1995  ...         1   0       0
2         3  Four Rooms (1995)  01-Jan-1995  ...         1   0       0
3         4  Get Shorty (1995)  01-Jan-1995  ...         0   0       0
4         5     Copycat (1995)  01-Jan-1995  ...         1   0       0

[5 rows x 24 columns]

In [6]:
occupation.head(5)

   administrator
0         artist
1         doctor
2       educator
3       engineer
4  entertainment

In [7]:
user.head(5)

   user_id  age sex  occupation zip_code
0        1   24   M  technician    85711
1        2   53   F       other    94043
2        3   23   M      writer    32067
3        4   24   M  technician    43537
4        5   33   F       other    15213

In [8]:
#Посчитайте среднюю оценку, которую поставил каждый пользователь
data.groupby('user_id')['rating'].mean().reset_index(name='avg_rating')

     user_id  avg_rating
0          1    3.610294
1          2    3.709677
2          3    2.796296
3          4    4.333333
4          5    2.874286
5          6    3.635071
6          7    3.965261
7          8    3.796610
8          9    4.272727
9         10    4.206522
10        11    3.464088
11        12    4.392157
12        13    3.097484
13        14    4.091837
14        15    2.875000
15        16    4.328571
16        17    3.035714
17        18    3.880866
18        19    3.550000
19        20    3.104167
20        21    2.670391
21        22    3.351562
22        23    3.635762
23        24    4.323529
24        25    4.051282
25        26    2.943925
26        27    3.240000
27        28    3.721519
28        29    3.647059
29        30    3.767442
..       ...         ...
913      914    3.086957
914      915    3.115385
915      916    3.365931
916      917    3.542857
917      918    3.349515
918      919    3.470046
919      920    3.230769
920      921    3.272727
921      922    3.370079
922      923    4.148649
923      924    3.756098
924      925    3.125000
925      926    3.300000
926      927    3.691667
927      928    4.687500
928      929    3.693878
929      930    2.968254
930      931    3.721311
931      932    3.966805
932      933    2.646739
933      934    3.701149
934      935    3.923077
935      936    3.746479
936      937    3.375000
937      938    3.268519
938      939    4.265306
939      940    3.457944
940      941    4.045455
941      942    4.265823
942      943    3.410714

[943 rows x 2 columns]

In [9]:
#Отсортируйте фильмы по количеству оценок
data.groupby('movie_id')['rating'].count().reset_index(name='amount').sort_values(['amount'], ascending=False) 

#.reset_index(name='amount').sort_values(['amount'], axis=0)

      movie_id  amount
49          50     583
257        258     509
99         100     508
180        181     507
293        294     485
285        286     481
287        288     478
0            1     452
299        300     431
120        121     429
173        174     420
126        127     413
55          56     394
6            7     392
97          98     390
236        237     384
116        117     378
171        172     367
221        222     365
312        313     350
203        204     350
404        405     344
78          79     336
209        210     331
150        151     326
172        173     324
68          69     321
747        748     316
167        168     316
268        269     315
...        ...     ...
1339      1340       1
1338      1339       1
1594      1595       1
1595      1596       1
1328      1329       1
1598      1599       1
1324      1325       1
1600      1601       1
1602      1603       1
1603      1604       1
1582      1583       1
1580      1581       1
1563      1564       1
1579      1580       1
1564      1565       1
1565      1566       1
1566      1567       1
1567      1568       1
1568      1569       1
1569      1570       1
1570      1571       1
1571      1572       1
1348      1349       1
1573      1574       1
1574      1575       1
1575      1576       1
1576      1577       1
1347      1348       1
1578      1579       1
1681      1682       1

[1682 rows x 2 columns]

In [10]:
#Средствами pandasa соедините данные по оценкам с данными 
#по пользователям (u.user)
user_ext = user.merge(data, left_on='user_id', right_on='user_id')
print(user_ext)

       user_id  age sex  occupation zip_code  movie_id  rating  unix_timestamp
0            1   24   M  technician    85711        61       4       878542420
1            1   24   M  technician    85711       189       3       888732928
2            1   24   M  technician    85711        33       4       878542699
3            1   24   M  technician    85711       160       4       875072547
4            1   24   M  technician    85711        20       4       887431883
5            1   24   M  technician    85711       202       5       875072442
6            1   24   M  technician    85711       171       5       889751711
7            1   24   M  technician    85711       265       4       878542441
8            1   24   M  technician    85711       155       2       878542201
9            1   24   M  technician    85711       117       3       874965739
10           1   24   M  technician    85711        47       4       875072125
11           1   24   M  technician    85711       222       4       878873388
12           1   24   M  technician    85711       253       5       874965970
13           1   24   M  technician    85711       113       5       878542738
14           1   24   M  technician    85711       227       4       876892946
15           1   24   M  technician    85711        17       3       875073198
16           1   24   M  technician    85711        90       4       878542300
17           1   24   M  technician    85711        64       5       875072404
18           1   24   M  technician    85711        92       3       876892425
19           1   24   M  technician    85711       228       5       878543541
20           1   24   M  technician    85711       266       1       885345728
21           1   24   M  technician    85711       121       4       875071823
22           1   24   M  technician    85711       114       5       875072173
23           1   24   M  technician    85711       132       4       878542889
24           1   24   M  technician    85711        74       1       889751736
25           1   24   M  technician    85711       134       4       875073067
26           1   24   M  technician    85711        98       4       875072404
27           1   24   M  technician    85711       186       4       875073128
28           1   24   M  technician    85711       221       5       887431921
29           1   24   M  technician    85711        84       4       875072923
...        ...  ...  ..         ...      ...       ...     ...             ...
99970      943   22   M     student    77841        50       4       875501835
99971      943   22   M     student    77841       367       4       888639679
99972      943   22   M     student    77841       585       1       888640250
99973      943   22   M     student    77841       427       4       888639147
99974      943   22   M     student    77841       185       2       888639370
99975      943   22   M     student    77841       403       4       888639746
99976      943   22   M     student    77841       401       1       888639867
99977      943   22   M     student    77841       576       4       888640106
99978      943   22   M     student    77841       717       4       875502116
99979      943   22   M     student    77841       216       4       888639327
99980      943   22   M     student    77841       763       4       875501813
99981      943   22   M     student    77841        69       5       888639427
99982      943   22   M     student    77841       168       2       888638897
99983      943   22   M     student    77841       526       4       888639523
99984      943   22   M     student    77841       196       5       888639192
99985      943   22   M     student    77841         9       3       875501960
99986      943   22   M     student    77841       672       5       888640125
99987      943   22   M     student    77841        38       3       888640208
99988      943   22   M     student    77841       274       3       875502074
99989      943   22   M     student    77841       568       3       888639042
99990      943   22   M     student    77841       139       1       888640027
99991      943   22   M     student    77841       825       3       875502283
99992      943   22   M     student    77841       193       4       888639093
99993      943   22   M     student    77841       470       4       888639814
99994      943   22   M     student    77841      1047       2       875502146
99995      943   22   M     student    77841       415       1       888640027
99996      943   22   M     student    77841       219       4       888639575
99997      943   22   M     student    77841       796       3       888640311
99998      943   22   M     student    77841       739       4       888639929
99999      943   22   M     student    77841       391       2       888640291

[100000 rows x 8 columns]

In [11]:
#Построить модель, которая предсказывает оценку для фильма и пользователя 
#(воспользоваться RandomForestRegressor, тк мы решаем задачу регрессии)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from datetime import date


df = user_ext.merge(item, left_on='movie_id', right_on='movie_id')


del df['unix_timestamp']
del df['movie_id']
del df['user_id']
del df['zip_code']
del df['video_release_date']
del df['imdb_url']
del df['title']

target = df['rating']
del df['rating']

df.sex = pd.factorize(df.sex)[0]
df.sex = pd.Categorical(df.sex)

date_map = {
    'jan': 0,
    'feb': 1,
    'mar': 2,
    'apr': 3,
    'may': 4,
    'jun': 5,
    'jul': 6,
    'aug': 7,
    'sep': 8,
    'oct': 9,
    'nov': 10,
    'dec': 11
}

def convert_date(x):
  try:
    if type(x) != str:
      return 0
    arr = x.lower().split('-')
    year = int(arr[2])
    month = date_map[arr[1]]
    day = int(arr[0])
    
    d = date(year, month + 1, day)
    
    ordinal = d.toordinal()
    return ordinal
  
  except Exception as err:
    print('err = ', err)
    return 0
  
df['release_date'] = df['release_date'].apply(convert_date)

df = pd.get_dummies(df, columns=['occupation'], prefix=['occupation'])

pd.set_option('display.max_columns', 500)

X_train, X_test, y_train, y_test = train_test_split(df, target)
model = RandomForestRegressor(max_depth=2, random_state=43, n_estimators=120)
model.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=2,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=120,
                      n_jobs=None, oob_score=False, random_state=43, verbose=0,
                      warm_start=False)

In [12]:
#Оценить качество регрессора на отложенной (train_test_split) выборке по одной из метрик на выбор - RMSE, RMAE, R^2
import numpy as np
from sklearn.metrics import mean_squared_error
print(model.score(X_test, y_test))
predicts = model.predict(X_test)
print('mean_squared_error = ', mean_squared_error(predicts, y_test))
df1 = pd.DataFrame({'prediction': predicts, 'real': np.array(y_test)})
df1.prediction = df1.prediction.apply(lambda x: round(x))
print(df1)

0.048938732633618254
mean_squared_error =  1.1962134527244435
       prediction  real
0               3     5
1               4     4
2               4     5
3               3     2
4               3     5
5               3     4
6               4     3
7               3     5
8               4     4
9               3     2
10              3     2
11              4     4
12              3     4
13              4     4
14              4     2
15              4     2
16              3     2
17              4     4
18              4     4
19              3     5
20              3     3
21              4     5
22              3     1
23              3     3
24              4     2
25              4     5
26              4     4
27              3     4
28              4     4
29              4     3
...           ...   ...
24970           4     3
24971           4     5
24972           3     4
24973           4     3
24974           3     4
24975           3     5
24976           4     4
24977           4     5
24978           3     4
24979           4     3
24980           3     5
24981           3     5
24982           3     3
24983           4     3
24984           4     4
24985           3     4
24986           3     4
24987           3     3
24988           4     4
24989           4     4
24990           3     4
24991           3     3
24992           4     4
24993           3     2
24994           3     5
24995           4     5
24996           4     4
24997           4     1
24998           4     4
24999           4     4

[25000 rows x 2 columns]

In [0]:
#Загрузить данные в spark
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://www-us.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz
!tar xf spark-2.4.3-bin-hadoop2.7.tgz
!pip install -q findspark

In [0]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.4.3-bin-hadoop2.7"

In [0]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

In [0]:
from pyspark.sql.types import StructType, StructField, StringType, IntegerType

In [17]:
d_schema = StructType([
    StructField("user_id", IntegerType(), True), 
    StructField("movie_id", IntegerType(), True),
    StructField("rating", IntegerType(), True),
    StructField("unix_timestamp", IntegerType(), True)
])

data = spark.read.options(delimiter="\t").csv('u.data', header=False, schema=d_schema)
data.show(4)

+-------+--------+------+--------------+
|user_id|movie_id|rating|unix_timestamp|
+-------+--------+------+--------------+
|    196|     242|     3|     881250949|
|    186|     302|     3|     891717742|
|     22|     377|     1|     878887116|
|    244|      51|     2|     880606923|
+-------+--------+------+--------------+
only showing top 4 rows

In [18]:
g_schema = StructType([
    StructField("genre", StringType(), True), 
    StructField("index", IntegerType(), True),
])

genre = spark.read.options(delimiter='|').csv('u.genre', header=False, schema=g_schema)
genre.show(40)

+-----------+-----+
|      genre|index|
+-----------+-----+
|    unknown|    0|
|     Action|    1|
|  Adventure|    2|
|  Animation|    3|
| Children's|    4|
|     Comedy|    5|
|      Crime|    6|
|Documentary|    7|
|      Drama|    8|
|    Fantasy|    9|
|  Film-Noir|   10|
|     Horror|   11|
|    Musical|   12|
|    Mystery|   13|
|    Romance|   14|
|     Sci-Fi|   15|
|   Thriller|   16|
|        War|   17|
|    Western|   18|
+-----------+-----+

In [19]:
m_schema = StructType([
    StructField('movie_id', IntegerType(), True),
    StructField('title', StringType(), True),
    StructField('release_date', StringType(), True),
    StructField('video_release_date', StringType(), True),
    StructField('imdb_url', StringType(), True),
    StructField('unknown', IntegerType(), True),
    StructField('action', IntegerType(), True),
    StructField('adventure', IntegerType(), True),
    StructField('animation', IntegerType(), True),
    StructField('children\'s', IntegerType(), True),
    StructField('comedy', IntegerType(), True),
    StructField('crime', IntegerType(), True),
    StructField('documentary', IntegerType(), True),
    StructField('drama', IntegerType(), True),
    StructField('fantasy', IntegerType(), True),
    StructField('film-noir', IntegerType(), True),
    StructField('horror', IntegerType(), True),
    StructField('musical', IntegerType(), True),
    StructField('mystery', IntegerType(), True),
    StructField('romance', IntegerType(), True),
    StructField('sci-fi', IntegerType(), True),
    StructField('thriller', IntegerType(), True),
    StructField('war', IntegerType(), True),
    StructField('western', IntegerType(), True),
])

item = spark.read.options(delimiter="|").csv("u.item", header=False, schema=m_schema)
item.show(3)

+--------+-----------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie_id|            title|release_date|video_release_date|            imdb_url|unknown|action|adventure|animation|children's|comedy|crime|documentary|drama|fantasy|film-noir|horror|musical|mystery|romance|sci-fi|thriller|war|western|
+--------+-----------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|       1| Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        1|         1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       2| GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|        0|         0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       3|Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
+--------+-----------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 3 rows

In [20]:
o_schema = StructType([
    StructField("occupation", StringType(), True)
])

occupation = spark.read.options(delimiter=' ').csv('u.occupation', header=False, schema=o_schema)
occupation.show(40)

+-------------+
|   occupation|
+-------------+
|administrator|
|       artist|
|       doctor|
|     educator|
|     engineer|
|entertainment|
|    executive|
|   healthcare|
|    homemaker|
|       lawyer|
|    librarian|
|    marketing|
|         none|
|        other|
|   programmer|
|      retired|
|     salesman|
|    scientist|
|      student|
|   technician|
|       writer|
+-------------+

In [21]:
u_schema = StructType([
    StructField("user_id", StringType(), True),
    StructField("age", StringType(), True),
    StructField("sex", StringType(), True),
    StructField("occupation", StringType(), True),
    StructField("zip_code", StringType(), True),
])
user = spark.read.options(delimiter="|").csv("u.user", header=False, schema=u_schema)
user.show(5)

+-------+---+---+----------+--------+
|user_id|age|sex|occupation|zip_code|
+-------+---+---+----------+--------+
|      1| 24|  M|technician|   85711|
|      2| 53|  F|     other|   94043|
|      3| 23|  M|    writer|   32067|
|      4| 24|  M|technician|   43537|
|      5| 33|  F|     other|   15213|
+-------+---+---+----------+--------+
only showing top 5 rows

In [22]:
i_schema = StructType([
    StructField("amount", IntegerType(), True),
    StructField("type", StringType(), True)
])

info = spark.read.options(delimiter=" ").csv("u.info", header=False, schema=i_schema)

info.show()

+------+-------+
|amount|   type|
+------+-------+
|   943|  users|
|  1682|  items|
|100000|ratings|
+------+-------+

In [23]:
#Средствами спарка вывести среднюю оценку для каждого фильма
import pyspark.sql.functions as F
mean_rating = data.groupBy("movie_id").agg(F.mean("rating").alias("Mean"))
mean_rating = mean_rating.withColumn("Mean", F.round(mean_rating["Mean"], 2))
mean_rating.show(20)

+--------+----+
|movie_id|Mean|
+--------+----+
|     496|4.12|
|     471|3.61|
|     463|3.86|
|     148| 3.2|
|    1342| 2.5|
|     833| 3.2|
|    1088|2.23|
|    1591|3.17|
|    1238|3.13|
|    1580| 1.0|
|    1645| 4.0|
|     392|3.54|
|     623|2.92|
|     540|2.51|
|     858| 1.0|
|     737|2.98|
|     243|2.44|
|    1025|2.93|
|    1084|3.86|
|    1127|2.91|
+--------+----+
only showing top 20 rows

In [24]:
data_ext = data.join(item, on=["movie_id"], how="left_outer")
data_ext.show(5)

+--------+-------+------+--------------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie_id|user_id|rating|unix_timestamp|               title|release_date|video_release_date|            imdb_url|unknown|action|adventure|animation|children's|comedy|crime|documentary|drama|fantasy|film-noir|horror|musical|mystery|romance|sci-fi|thriller|war|western|
+--------+-------+------+--------------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|     242|    196|     3|     881250949|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|     302|    186|     3|     891717742|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
|     377|     22|     1|     878887116| Heavyweights (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|         1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      51|    244|     2|     880606923|Legends of the Fa...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|
|     346|    166|     1|     886397596| Jackie Brown (1997)| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+--------+-------+------+--------------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [25]:
#В спарке получить 2 датафрейма с 5-ю самыми популярными 
#и самыми непопулярными фильмами 
#(по количеству оценок, либо по самой оценке - на Ваш выбор)
most_popular = data_ext.groupBy(["movie_id", "title"]).agg(F.count("rating").alias("Count")).orderBy("Count", ascending=False)
most_popular[["title", "Count"]].show(5)

+--------------------+-----+
|               title|Count|
+--------------------+-----+
|    Star Wars (1977)|  583|
|      Contact (1997)|  509|
|        Fargo (1996)|  508|
|Return of the Jed...|  507|
|    Liar Liar (1997)|  485|
+--------------------+-----+
only showing top 5 rows

In [26]:
least_popular = data_ext.groupBy(["movie_id", "title"]).agg(F.count("rating").alias("Count")).orderBy("Count", ascending=True)
least_popular[["title", "Count"]].show(5)

+--------------------+-----+
|               title|Count|
+--------------------+-----+
|War at Home, The ...|    1|
|Invitation, The (...|    1|
|     Deceiver (1997)|    1|
|Wend Kuuni (God's...|    1|
|King of New York ...|    1|
+--------------------+-----+
only showing top 5 rows

In [27]:
#Средствами спарка соедините информацию по фильмам и жанрам (u.genre)
from functools import reduce
genre_list = [x.asDict()['genre']  for x in genre.select('genre').collect()]  

data_frames = [item.crossJoin(genre).filter((F.col('genre') == g) & (F.col(g) == 1))[['movie_id', 'title', 'genre']] for g in genre_list]
print([df.count() for df in data_frames])

df_union = reduce(lambda df1, df2: df1.union(df2), data_frames)
print(df_union.count())

df_union.show(50)

[2, 251, 135, 42, 122, 505, 109, 50, 725, 22, 24, 92, 56, 61, 247, 101, 251, 71, 27]
2893
+--------+--------------------+-------+
|movie_id|               title|  genre|
+--------+--------------------+-------+
|     267|             unknown|unknown|
|    1373| Good Morning (1971)|unknown|
|       2|    GoldenEye (1995)| Action|
|       4|   Get Shorty (1995)| Action|
|      17|From Dusk Till Da...| Action|
|      21|Muppet Treasure I...| Action|
|      22|   Braveheart (1995)| Action|
|      24|Rumble in the Bro...| Action|
|      27|     Bad Boys (1995)| Action|
|      28|    Apollo 13 (1995)| Action|
|      29|Batman Forever (1...| Action|
|      33|    Desperado (1995)| Action|
|      39| Strange Days (1995)| Action|
|      50|    Star Wars (1977)| Action|
|      53|Natural Born Kill...| Action|
|      54|     Outbreak (1995)| Action|
|      62|     Stargate (1994)| Action|
|      68|    Crow, The (1994)| Action|
|      73|     Maverick (1994)| Action|
|      74|Faster Pussycat! ...| Action|
|      79|Fugitive, The (1993)| Action|
|      80|Hot Shots! Part D...| Action|
|      82|Jurassic Park (1993)| Action|
|      92| True Romance (1993)| Action|
|      96|Terminator 2: Jud...| Action|
|     101|  Heavy Metal (1981)| Action|
|     110|Operation Dumbo D...| Action|
|     117|    Rock, The (1996)| Action|
|     118|      Twister (1996)| Action|
|     121|Independence Day ...| Action|
|     127|Godfather, The (1...| Action|
|     128|     Supercop (1992)| Action|
|     144|     Die Hard (1988)| Action|
|     145|Lawnmower Man, Th...| Action|
|     147|Long Kiss Goodnig...| Action|
|     148|Ghost and the Dar...| Action|
|     161|      Top Gun (1986)| Action|
|     164|   Abyss, The (1989)| Action|
|     172|Empire Strikes Ba...| Action|
|     173|Princess Bride, T...| Action|
|     174|Raiders of the Lo...| Action|
|     176|       Aliens (1986)| Action|
|     177|Good, The Bad and...| Action|
|     181|Return of the Jed...| Action|
|     183|        Alien (1979)| Action|
|     184|Army of Darkness ...| Action|
|     186|Blues Brothers, T...| Action|
|     187|Godfather: Part I...| Action|
|     188|Full Metal Jacket...| Action|
|     195|Terminator, The (...| Action|
+--------+--------------------+-------+
only showing top 50 rows

In [28]:
#Посчитайте средствами спарка среднюю оценку для каждого жанра
#1 способ
for row in genre.select('genre').distinct().collect():
  g = row.asDict()['genre'].lower()
  score = data_ext.groupBy(g).agg(F.mean('rating').alias('avg')).filter(F.col(g) == 1).select('avg').collect()[0].asDict()['avg']
  print(g + ': ', score)

crime:  3.6322780881440098
romance:  3.621704948358255
thriller:  3.5090069495245064
adventure:  3.503526503308369
unknown:  3.2
children's:  3.3532442216652742
drama:  3.6873793708484772
war:  3.815811874866993
documentary:  3.6728232189973613
fantasy:  3.2152366863905324
mystery:  3.63813155386082
musical:  3.521396851029471
animation:  3.5766990291262135
film-noir:  3.9215233698788228
horror:  3.2903893172841827
western:  3.6132686084142396
comedy:  3.3940734781442745
action:  3.480245417953027
sci-fi:  3.5607227022780834

In [29]:
#2 способ
df_union_ext = df_union.join(data, on=["movie_id"], how="left_outer")
df_union_ext = df_union_ext.groupBy('genre').mean('rating')
df_union_ext.show(20)

+-----------+------------------+
|      genre|       avg(rating)|
+-----------+------------------+
|      Crime|3.6322780881440098|
|    Romance| 3.621704948358255|
|   Thriller|3.5090069495245064|
|  Adventure| 3.503526503308369|
|    unknown|               3.2|
| Children's|3.3532442216652742|
|      Drama|3.6873793708484772|
|        War| 3.815811874866993|
|Documentary|3.6728232189973613|
|    Fantasy|3.2152366863905324|
|    Mystery|  3.63813155386082|
|    Musical| 3.521396851029471|
|  Animation|3.5766990291262135|
|  Film-Noir|3.9215233698788228|
|     Horror|3.2903893172841827|
|    Western|3.6132686084142396|
|     Comedy|3.3940734781442745|
|     Action| 3.480245417953027|
|     Sci-Fi|3.5607227022780834|
+-----------+------------------+

In [0]:
#Теоретическая часть
#Вы - главный по данным в среднем по объему просмотров интернет-кинотеатре. 
#Ваша задача разработать стратегию внедрения хранилища данных и работы с большими данными в этой компании.

In [0]:
#Описать основные имеющиеся данные и источники их поступления

#Просмотренные фильмы пользователя
#Оценки, поставленные пользователем(числа)
#Отзывы(текст), теги поставленные пользователями сайта
#Анкета пользователя, его предпочтения
#Поведение пользователя на сайте
#Внешние рецензии на фильмы
#Метаданные фильма(актеры, режесер, жанры)
#Рейтинг IMDB Кинопоиск

In [0]:
#Сформулировать цель проекта и ключевые метрики, на которые мы будем влиять

#Если я отвечаю за онлайн кинотеатр, то основной моей целью будет наполнить 
#витрину кинотеатра интересными и востребованными фильмами.
#Нужно, чтобы клиенты во-первых смотрели фильмы, во-вторых они им нравились.

#Бизнес он-лайн кинотеатра состоит в принятии решения: приобретать ли фильм для проката или нет.

#Чтобы это сделать, нужно анализировать следующие параметры:
#1)жанры и их средний рейтинг
#2)жанры и количество просмотров  
#3)метаданные(актеры, режиссеры) и количество просмотров
#4)метаданные(актеры, режиссеры) и отзывы на похожие фильмы с теми же актерами и режиссерами
#5)статистика конкурентов по ключевым параметрам: рейтинги, отзывы, количество просмотров(по возможности)
#6)учет рейтинга ожиданий (стороннего, например Кинопоиска)

#Метрики на которые можно влиять: используя большие данные мы можем делать предположения (используя машинное обучение)
#о предпочтениях пользователей и можем рекомендовать подходящие фильмы пользователям, которые за просмотр платят, а также 
#закупать более востребованные фильмы. Здесь несколько метрик: 1)лояльность клиента(если сервис клиента устраивает, 
#то он долго будет пользоваться нашим кинотеатром). 2)принятие клиентами решений о подписке (если набор фильмов, 
#представленный в кинотеатре - представляет для клиента интерес, то он принимает решение о подписке).

#Другой целевой показатель - 3)частота покупок фильмов клиентами (1 раза в месяц или 5 раз в месяц - это имеет значение). 
#В данном случае метрикой будет - доход от продажи фильмов, на который мы будем влиять.

#И еще одна целевая метрика - 
#это 4)время пребывания клиента на сайте (время пребывания на сайте - улучшает показатели CEO 
#и увеличивает доход от рекламы на сайте).

In [0]:
#Описать основные сущности в хранилище данных
#пользователи (персональные данные)
#фильмы (метаданные: актеры, режиссеры, жанры)
#оценки пользователя для каждого фильма(рейтинги)
#отзывы пользователя, комментарии
#теги 
#просмотры (время просмотра, продолжительность просмотра, количество раз, были ли скачивания или просмотр онлайн)
#пользовательские счета (баланс пользователя, плата за подписки, плата за купленные фильмы)
#устройства пользователя и ip адреса

In [0]:
#Описать основные проверки на качество данных (10-20 штук)
#1)проверка баланса пользователя, достаточно ли денежных средств, чтобы осуществить подписку или покупку фильма
#2)проверка формата емайла для осуществления в дальнейшем емайл рассылки для клиента 
#3)проверки имени и фамилии пользователя (не должно быть цифр, не меньше 2- букв)
#4)возраст пользователя (от 18 до 99 лет, возраст должен быть числом)
#5)проверка номера банковской карты
#6)проверка комментариев на отсутствие нецензурной лексики
#7)проверка того, что если пользователь оценивает фильм, то он может сделать это только один раз (с данного аккаунта)
#8)проверка того, что данный емайл и телефон пока еще не зарегистрированны в данной базе данных
#9)проверка тегов по длине и на адекватность
#10)проверка пола пользователя 
#11)проверка данных о местоположении клиента (если лицензия на прокат фильма выдана на конкретную страну)
#12)проверка корректности устройств пользователя и ip адреса (пользователь не вводит эти данные, но запрос может быть осуществен)

In [0]:
#Описать основные бизнес-отчеты, которые мы сможем построить из имеющегося хранилища данных

#внутренний рейтинг просмотров (какие фильмы смотрят больше, какие меньше)

#через сколько времени после начала использования онлайн кинотеатра была сделана подписка

#процент пользователей, использующих подписку в течении данного периода

#статистика по частично просмотренным фильмам (сколько их, какая часть фильма просмотрена, время просмотра)

#какие фильмы больше покупают, какие меньше (по жанрам, по годам, по актерам, по режиссерам)

#рейтинги, проставленные клиентами за период

#отчет по ожиданиям пользователя(насколько ожидания пользователя оправдались после покупки фильма: на основе времени просмотра, рейтинга и отзывов)

#статистика по продлению подписки(% не продливших, % продливших с задержкой и какой задержкой, 
#% установивших автопродление, % досрочно отписавшихся)

#статистика захода на сайт: время, дни недели, выходные и праздники, время года

#время пребывания на сайте

In [0]:
#Описать основные DS-модели, которые мы сможем построить на основе имеющихся данных

#Рекомендательные системы
#Данная DS модель эффективно может быть применена для предоставления рекомендаций клиентам на основе:
#колабаративной фильтрации(при определении похожих пользователей на основе их оценок и текстовых отзывов),
#а также рекомендательная система на основе content based (определяем характеристики фильмов (жанры, актеры, режисер итд), 
#которые пользователь высоко оценил и предлагаем похожие).
#Таким образом, мы можем предлагать полее подходящие фильмы для клиентов.

#Система ранжирования 
#Система ранжирования необходима для определения приоритетов для осуществления закупки фильмов у производителя.
#Ранжирование выстраивается на основе таких данных как: извлекаем характеристики фильмов, 
#которые просматривают больше всего (для понимания какие жанры(актеров, режисеров) наша аудитория предпочитает итд).
#Далее анализируем внешние данные: рецензии, рейтинги для новых фильмов. Анализируем информацию от конкурентов.

#Система регрессионного анализа для принятие решения о цене подписки на основе данных для наших пользователей и 
#оценки данных пользователей конкурентов, а также анализ цены подписки конкурентов. Пытаемся предсказать изменение 
#прибыли при изменении цены абонемента на основе собранных данных, а также сохраняем статистику о реакции изменения прибыли 
#на изменение цены абонемента для улучшения будущих прогнозов.

#Данная система регрессионного анализа может быть дополнена системой лояльности (акции, скидки, промокоды) 
#на базе использования аналогичного подхода.

#Задачи классификации
#Достаточно обширны для любого бизнеса,особенно на уровне топ-менеджмента, в том числе походят для принятия решенией.
#Для онлайн кинотеатра бинарными решениями могут быть: 
#-замена страницы вебсайта сервиса(из-за прохого юзабилити, клиент нае доходит до покупки),
#-целесообразность размещения рекламы на сайте (проводим или непроводим),
#-целесообразность емайл рассылки клиентам,
#-целесообразность расширения технических мощностей итд.

In [0]:
#Описать источники внешних данных и какой value они смогут дать
#1)Рейтинг IMDB Кинопоиск
#2)статистика конкурентов по ключевым параметрам: рейтинги, отзывы, количество просмотров
#3)рейтинг ожиданий
#value - понимание того, какие подходящие фильмы стоит приобрететь для увеличения 
#лояльности клиентов по подписке и росту числа покупок фильмов

#4)внешние сайты и youtube для поиска пиратского контента
#value - предотвращение снжения интереса к сайту онлайн кинотеатра